import _ from "lodash";
const labelMapping = {
  d_Status: { title: "Doors Status" },
  w_Status: { title: "Windows Status" },
  m_Status: { title: "Status" },
  m_BranchId: { title: "Branch" },
  m_ManufacturingFacility: { title: "Manufacturing Facility" },
  d_ManufacturingFacility: { title: "Doors Manufacturing Facility" },
  w_ManufacturingFacility: { title: "Windows Manufacturing Facility" },
  
  m_ShippingType: { title: "Shipping Type" },
  m_ResidentialType: { title: "Residential Type" },
  m_JobType: { title: "Job Type" },
  m_CustomerType: { title: "Customer Type" },
  m_Project: { title: "Project" },
  m_SalesRep: { title: "Sales Reps" },
  m_SalesRepKeyAccount: { title: "Sales Reps" },
  
  d_BlockNo: { title: "Doors Block NO." },
  d_BatchNo: { title: "Doors Batch NO." },
  d_GlassSupplier: { title: "Doors Glass Supplier" },
  w_BlockNo: { title: "Windows Block NO." },
  w_BatchNo: { title: "Windows Batch NO." },
  w_GlassSupplier: { title: "Windows Glass Supplier" },
  w_GlassOptions: { title: "Windows Glass Option" },
  m_SiteContact: { title: "Site Contact" },
  m_SiteContactPhoneNumber: { title: "Site Contact Number" },
  m_SiteContactEmail: { title: "Site Contact Email" },
  m_CustomerName: { title: "Customer Name" },
  m_ProjectName: { title: "Project Name" },
  m_ProjectManager: { title: "Project Manager" },
  m_Comment_1: { title: "Comment" },
  m_City: { title: "City" },
  m_Address: { title: "Address" },
  m_Email: { title: "Email" },
  m_PhoneNumber: { title: "Phone Number" },
  m_OtherContactNumber: { title: "Other Contact Number" },
  m_CustomerPickup: { title: "Customer Pick-up" },
  m_Community: { title: "Community" },
  d_RushOrder: { title: "Doors Rush Order" },
  d_PaintIcon: { title: "Doors Paint Icon" },
  d_RBMIcon: { title: "Doors RBM Icon" },
  d_GridsRequired: { title: "Doors Grids Required" },
  d_WaterTestingRequired: { title: "Doors Water Testing Required" },
  d_MiniblindIcon: { title: "Doors Mini Blind" },
  d_EngineeredIcon: { title: "Doors Engineered Order Icon" },
  d_ShapesRequires: { title: "Doors Shapes Requires" },
  w_RushOrder: { title: "Windows Rush Order" },
  w_PaintIcon: { title: "Windows Paint Icon" },
  w_CapstockIcon: { title: "Capstock Icon" },
  w_MiniblindIcon: { title: "Windows Miniblind Icon" },
  w_EngineeredIcon: { title: "Windows Engineered Order Icon" },
  w_RBMIcon: { title: "Windows RBM Icon" },
  w_VinylWrapIcon: { title: "Vinyl Wrap Icon" },
  w_ShapesRequires: { title: "Windows Shapes Requires" },
  w_GridsRequired: { title: "Windows Grids Required" },
  w_WaterTestingRequired: { title: "Windows Water Testing Required" },
  w_WaterPenetrationResistance: { title: "Water Penetration Resistance" },
  m_ShippingStartDate: { title: "Shipping Date" },
  m_ShippingEndDate: false, // { title: "Shipping End" },
  m_RevisedDeliveryDate: { title: "Revised Delivery Date" },
  d_CustomerDate: { title: "Doors Customer Date" },
  d_ProductionStartDate: { title: "Doors Production Date" },
  d_PaintStartDate: { title: "Doors Paint Date" },
  d_PaintEndDate: false, //{ title: "Doors Paint End" },
  d_GlassOrderDate: { title: "Doors Glass Order Date" },
  w_CustomerDate: { title: "Windows Customer Date" },
  w_ProductionStartDate: { title: "Windows Production Date" },
  w_PaintStartDate: { title: "Windows Paint Date" },
  w_PaintEndDate: false, //{ title: "Windows Paint End" },
  w_GlassOrderDate: { title: "Windows Glass Order Date" },
  w_GlassRecDate: { title: "Windows Glass Receive Date" },
  m_CustomerDate: { title: "Customer Date" },
  w__26CA: { title: "26CA" },
  w__26CAMin: { title: "26CA Min" },
  w__26HY: { title: "26HY" },
  w__26HYMin: { title: "26HY Min" },
  w__27DS: { title: "27DS" },
  w__27DSMin: { title: "27DS Min" },
  w__29CA: { title: "29CA" },
  w__29CAMin: { title: "29CA Min" },
  w__29CM: { title: "29CM" },
  w__29CMMin: { title: "29CM Min" },
  w__52PD: { title: "52PD" },
  w__52PDMin: { title: "52PD Min" },
  w__61DR: { title: "61DR" },
  w__61DRMin: { title: "61DR Min" },
  w__68CA: { title: "68CA" },
  w__68CAMin: { title: "68CA Min" },
  w__68SL: { title: "68SL" },
  w__68SLMin: { title: "68SL Min" },
  w__68VS: { title: "68VS" },
  w__68VSMin: { title: "68VS Min" },
  w__88SL: { title: "88SL" },
  w__88SLMin: { title: "88SL Min" },
  w__88VS: { title: "88VS" },
  w__88VSMin: { title: "88VS Min" },

  m_WorkOrderNo: { title: "Work Order" },
  m_Status_display: { title: "Order Status" },
  w_Status_display: { title: "Windows Status" },
  d_Status_display: { title: "Doors Status" },
  m_InstallStatus: { title: "Install Status" },
  m_FormStatus: { title: "Current Status" },
  m_Branch: { title: "Branch" },
  m_JobType: { title: "Job Type" },
  w_BatchNo: { title: "Windows Batch#" },
  w_BlockNo: { title: "Windows Block#" },
  d_BatchNo: { title: "Doors Batch#" },
  d_BlockNo: { title: "Doors Block#" },
  m_NumberOfWindows: { title: "Number of Windows" },
  m_NumberOfPatioDoors: { title: "Number of Patio Doors" },
  m_NumberOfDoors: { title: "Number of Exterior Doors" },
  m_NumberOfSwingDoors: { title: "Number of Swing Doors" },
  m_NumberOfOthers: { title: "Number of Others" },
  m_InvStatus: { title: "INV Status" },
  m_CreatedBy: { title: "Created By" },
  m_CreatedAt: { title: "Created At" },
  m_CreatedAt_display: { title: "Created At" },
  m_LastModifiedBy: { title: "Modified By" },
  m_LastModifiedAt_display: { title: "Modified At" },
  m_LastModifiedAt: { title: "Modified At" },
  m_ShippingNotes: {
    title: "Shipping Notes",
  },
  m_ProjectManagementNotes: {
    title: "Project Manager Notes",
  },
  m_ReturnTripNotes: {
    title: "Returned Job",
  },
  w_OfficeNotes: {
    title: "Windows Office Notes",
  },
  w_PlantNotes: {
    title: "Windows Plant Notes",
  },
  d_OfficeNotes: {
    title: "Doors Office Notes",
  },
  d_DoorShopNotes: {
    title: "Doors Shop",
  },

  // item level

  Item: { title: "Item" },
  System: { title: "System" },
  Description: { title: "Description" },
  DoorType: { title: "Doors Type" },
  Size: { title: "Size" },
  Quantity: { title: "Quantity" },
  SubQty: { title: "SubQty" },
  Notes: { title: "Notes" },
  DoorCutout: { title: "Doors Cut-out" },
  Status: { title: "Status" },
  Stock: { title: "Stock" },
  Lites: { title: "Lites" },
  BTO: { title: "BTO" },
  SlabPrep: { title: "Slab Prep" },
  Assembly: { title: "Assembly" },
  MillingDept: { title: "Milling Dept" },
  CustomSlabPrep: { title: "Custom Slab Prep" },
  QA: { title: "QA" },
  CustomMilling: { title: "Custom Milling" },
  TempSlab: { title: "TempSlab" },
  Painted: { title: "Painted" },
  BoxQty: { title: "Box Qty" },
  GlassQty: { title: "Glass Qty" },
  LBRMin: { title: "LBR Min" },
  RackLocation: { title: "Rack Location" },
  TransomCount: { title: "Transom Count" },
  SideliteCount: { title: "Sidelite Count" },
  SingleDoorCount: { title: "Single Doors Count" },
  DoubleDoorCount: { title: "Double Doors Count" },
  HighRisk: { title: "High Risk" },
  Custom: { title: "Custom" },
  RBMIcon: { title: "RBM Icon" },
  Wraped: { title: "Wraped" },
  PaintLineal: { title: "Paint Lineal" },
  // glass item level
  receivedExpected: { title: "Rcev. / Expt." },
  rackID: { title: "Rack ID" },
  rackType: { title: "Rack Type" },
  qty: { title: "Qty On Rack" },
  item: { title: "Item" },
  description: { title: "Description" },
  orderDate: { title: "Order Date" },
  shipDate: { title: "Shipping Date" },
  size: { title: "Size" },
  position: { title: "Position" },
  status: { title: "Status" },
  notes: { title: "Notes" },
  wi_Status:  { title: "Window Item Status" },
  di_Status:  { title: "Door Item Status" },

  // table list

  // hidden fields (should not show to front-end order history)
  d_Transom: false,
  d_Sidelite: false,
  d_SingleLiteFlag: false,
  d_MultiLiteFlag: false,
  d_SingleDoor: false,
  d_DoubleDoor: false,
  d_ProductionEndDate: false,

  // all same as master lvl
  d_CreatedById: false,
  d_CreatedBy: false,
  d_LastModifiedAt: false,
  d_LastModifiedById: false,
  d_LastModifiedBy: false,
  w_CreatedById: false,
  w_CreatedBy: false,

  w_LastModifiedAt: false,
  w_LastModifiedById: false,
  w_LastModifiedBy: false,
  // m_LastModifiedAt: false,
  m_LastModifiedById: false,
  // m_LastModifiedBy: false,
  m_CreatedById: false,

  // duplicated value
  m_WinStatus: false,
  m_DoorStatus: false,
  d_CurrentStateName: false, // same as stauts
  w_CurrentStateName: false,
  m_CurrentStateName: false,

  // removed
  d_PlantNotes: false, // only window
  d_WaterPenetrationResistance: false,

  d_IsActive: false, // sysem internal
  w_Id: false,
  w_MasterId: false,
  w_IsActive: false,
  d_Id: false,
  d_MasterId: false,
  m_IsActive: false,
  m_MasterId: false,
};

export const applyField = (arr) => {
  return arr.map((a) => {
    const _v = _.cloneDeep(a);
    if (!_v.title) {
      _v.title =
        labelMapping[a.id]?.title ||
        a.id ||
        labelMapping[a.key]?.title ||
        a.key;
    }
    return _v;
  });
};

export default labelMapping;
