import _ from 'lodash'
const labelMapping = {
  m_BranchId: { title: "Branch" },
  m_ManufacturingFacility: { title: "Manufacturing Facility" },
  m_ShippingType: { title: "Shipping Type" },
  m_ResidentialType: { title: "Residential Type" },
  m_JobType: { title: "Job Type" },
  m_CustomerType: { title: "Customer Type" },
  m_Project: { title: "Project" },
  m_SalesRep: { title: "Sales Reps" },
  d_BlockNo: { title: "Door Block NO." },
  d_BatchNo: { title: "Door Batch NO." },
  d_GlassSupplier: { title: "Door Glass Supplier" },
  w_BlockNo: { title: "Window Block NO." },
  w_BatchNo: { title: "Window Batch NO." },
  w_GlassSupplier: { title: "Window Glass Supplier" },
  w_GlassOptions: { title: "Window Glass Option" },
  m_SiteContact: { title: "Site Contact" },
  m_SiteContactPhoneNumber: { title: "Site Contact Number" },
  m_SiteContactEmail: { title: "Site Contact Email" },
  m_CustomerName: { title: "Customer Name" },
  m_ProjectName: { title: "Project Name" },
  m_ProjectManager: { title: "Project Manager" },
  m_Comment_1: { title: "Comment" },
  m_City: { title: "City" },
  m_Address: { title: "Address" },
  m_Email: { title: "Email" },
  m_PhoneNumber: { title: "Phone Number" },
  m_OtherContactNumber: { title: "Other Contact Number" },
  m_CustomerPickup: { title: "Customer Pick-up" },
  d_RushOrder: { title: "Door Rush Order" },
  d_PaintIcon: { title: "Door Paint Icon" },
  d_RBMIcon: { title: "Door RBM Icon" },
  d_GridIcon: { title: "Door Grids Required" },
  d_WaterTestingRequired: { title: "Door Water Testing Required" },
  d_MiniblindIcon: { title: "Door Mini Blind" },
  d_EngineeredIcon: { title: "Door Engineered Order Icon" },
  d_ShapesRequires: { title: "Door Shapes Requires" },
  w_RushOrder: { title: "Window Rush Order" },
  w_PaintIcon: { title: "Window Paint Icon" },
  w_CapstockIcon: { title: "Capstock Icon" },
  w_MiniblindIcon: { title: "Window Miniblind Icon" },
  w_EngineeredIcon: { title: "Window Engineered Order Icon" },
  w_RBMIcon: { title: "Window RBM Icon" },
  w_VinylWrapIcon: { title: "Vinyl Wrap Icon" },
  w_ShapesRequires: { title: "Window Shapes Requires" },
  w_GridIcon: { title: "Window Grids Required" },
  w_WaterTestingRequired: { title: "Window Water Testing Required" },
  w_WaterPenetrationResistance: { title: "Water Penetration Resistance" },
  m_ShippingStartDate: { title: "Shipping Date" },
  m_ShippingEndDate: { title: "Shipping End" },
  m_RevisedDeliveryDate: { title: "Revised Delivery Date" },
  d_CustomerDate: { title: "Door Customer Date" },
  d_ProductionStartDate: { title: "Doors Production Date" },
  d_PaintStartDate: { title: "Door Paint Date" },
  d_PaintEndDate: { title: "Door Paint End" },
  d_GlassOrderDate: { title: "Door Glass Order Date" },
  w_CustomerDate: { title: "Window Customer Date" },
  w_ProductionStartDate: { title: "Windows Production Date" },
  w_PaintStartDate: { title: "Window Paint Date" },
  w_PaintEndDate: { title: "Window Paint End" },
  w_GlassOrderDate: { title: "Window Glass Order Date" },
  w_GlassRecDate: { title: "Window Glass Receive Date" },
  w__26CA: { title: "26CA" },
  w__26CAMin: { title: "26CA Min" },
  w__26HY: { title: "26HY" },
  w__26HYMin: { title: "26HY Min" },
  w__27DS: { title: "27DS" },
  w__27DSMin: { title: "27DS Min" },
  w__29CA: { title: "29CA" },
  w__29CAMin: { title: "29CA Min" },
  w__29CM: { title: "29CM" },
  w__29CMMin: { title: "29CM Min" },
  w__52PD: { title: "52PD" },
  w__52PDMin: { title: "52PD Min" },
  w__61DR: { title: "61DR" },
  w__61DRMin: { title: "61DR Min" },
  w__68CA: { title: "68CA" },
  w__68CAMin: { title: "68CA Min" },
  w__68SL: { title: "68SL" },
  w__68SLMin: { title: "68SL Min" },
  w__68VS: { title: "68VS" },
  w__68VSMin: { title: "68VS Min" },

  m_ShippingNotes: {
    title: "Shipping Notes",
  },
  m_ProjectManagementNotes: {
    title: "Project Manager Notes",
  },
  m_ReturnTripNotes: {
    title: "Returned Job",
  },
  w_OfficeNotes: {
    title: "Window Office Notes",
  },
  w_PlantNotes: {
    title: "Window Plant Notes",
  },
  d_OfficeNotes: {
    title: "Door Office Notes",
  },
  d_DoorShopNotes: {
    title: "Door Shop",
  },

  // item level

  Item: { title: "Item" },
  System: { title: "System" },
  Description: { title: "Description" },
  DoorType: { title: "Door Type" },
  Size: { title: "Size" },
  Quantity: { title: "Quantity" },
  SubQty: { title: "SubQty" },
  Notes: { title: "Notes" },
  DoorCutout: { title: "Door Cut-out" },
  Status: { title: "Status" },
  Stock: { title: "Stock" },
  Lites: { title: "Lites" },
  BTO: { title: "BTO" },
  SlabPrep: { title: "Slab Prep" },
  Assembly: { title: "Assembly" },
  MillingDept: { title: "Milling Dept" },
  CustomSlabPrep: { title: "Custom Slab Prep" },
  QA: { title: "QA" },
  CustomMilling: { title: "Custom Milling" },
  TempSlab: { title: "TempSlab" },
  Painted: { title: "Painted" },
  BoxQty: { title: "Box Qty" },
  GlassQty: { title: "Glass Qty" },
  LBRMin: { title: "LBR Min" },
  RackLocation: { title: "Rack Location" },
  TransomCount: { title: "Transom Count" },
  SideliteCount: { title: "Sidelite Count" },
  SingleDoorCount: { title: "Single Door Count" },
  DoubleDoorCount: { title: "Double Door Count" },
  HighRisk: { title: "High Risk" },
  Custom: { title: "Custom" },
  RBMIcon: { title: "RBM Icon" },
  Wraped: { title: "Wraped" },
  PaintLineal: { title: "Paint Lineal" },
  // glass item level
  receivedExpected: { title: "Rcev. / Expt." },
  rackID: { title: "Rack ID" },
  rackType: { title: "Rack Type" },
  qty: { title: "Qty On Rack" },
  item: { title: "Item" },
  description: { title: "Description" },
  orderDate: { title: "Order Date" },
  shipDate: { title: "Shipping Date" },
  size: { title: "Size" },
  position: { title: "Position" },
  status: { title: "Status" },
  notes: { title: "Notes" },
};

export const applyField = (arr) => {
    return arr.map(a => {
        const _v = _.cloneDeep(a)
        if (!_v.title) {
            _v.title = labelMapping[a.id]?.title || a.id || labelMapping[a.key]?.title || a.key
        }
        return _v
    })
};

export default labelMapping;
